---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3319408299-lGSK1cFf90nO4smVuJALkJpZ4VSNlm08X5A2F8N
:access_token_secret: Nm3DoEzguEjSp3D7LzwA68hO60Vs2vV9asLDZ9MMi67YZ
